WIP: S3proxy
cfpb/hmda-platform pull request #4497
Opened 2022-07-14 19:06 UTC by kgudel

Addresses #4483

2022-09-14 17:00 UTC, meissadia commented
## Modified LAR
 
We also need to support MLAR files w/ header row
|Proxy|S3|
|---|----|
|/file/modifiedLar/year/<year\>/institution/<lei\>/txt|https://s3.amazonaws.com/cfpb-hmda-public/prod/modified-lar/<year\>/<lei\>.txt|
|/file/modifiedLar/year/<year\>/institution/<lei\>/htxt|https://s3.amazonaws.com/cfpb-hmda-public/prod/modified-lar/<year\>/<lei\>_header.txt|

2022-09-21 13:28 UTC, PatrickGoRaft requested changes

2022-09-22 17:17 UTC, PatrickGoRaft requested changes

2022-09-22 17:17 UTC, PatrickGoRaft commented on file-proxy/src/main/scala/hmda/uli/FileProxy.scala
> +package hmda.fileProxy
The package names don't correspond to the directory structure.

2022-09-22 17:17 UTC, PatrickGoRaft commented on file-proxy/src/main/resources/application.conf
> +akka.http.server.request-timeout = 4888888 seconds
Let's try setting this to `infinite`  to see if we can get around just setting some arbitrarily large value  ( I know we're doing this in other places in the code it'll be good to test it out here).

2022-09-22 17:17 UTC, PatrickGoRaft commented on file-proxy/src/main/scala/hmda/uli/api/http/ProxyHttpApi.scala
> +    val fStream: Future[Source[ByteString, NotUsed]] = retrieveData(s3Key).flatMap {
A map without later creating a Future should suffice here. Something we can note in a future refactor

2022-09-29 14:53 UTC, merged